// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSFFVBcx3qF7kakHhkw8g6ZxQ4xZDZ-MY',
    appId: '1:808859481275:web:277fdc51646678badae59e',
    messagingSenderId: '808859481275',
    projectId: 'go-app-3255c',
    authDomain: 'go-app-3255c.firebaseapp.com',
    databaseURL: 'https://go-app-3255c-default-rtdb.firebaseio.com',
    storageBucket: 'go-app-3255c.firebasestorage.app',
    measurementId: 'G-RLQPGLW44F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbN7OvIss1JrHLvQqIfcgSMqRZYJziaEU',
    appId: '1:808859481275:android:6509119f0bfbebafdae59e',
    messagingSenderId: '808859481275',
    projectId: 'go-app-3255c',
    databaseURL: 'https://go-app-3255c-default-rtdb.firebaseio.com',
    storageBucket: 'go-app-3255c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WzXLwhxO3iz3Alaqh9N9MzgerFT_zvk',
    appId: '1:808859481275:ios:39b4d3cf42cd0f23dae59e',
    messagingSenderId: '808859481275',
    projectId: 'go-app-3255c',
    databaseURL: 'https://go-app-3255c-default-rtdb.firebaseio.com',
    storageBucket: 'go-app-3255c.firebasestorage.app',
    iosBundleId: 'com.example.goDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6WzXLwhxO3iz3Alaqh9N9MzgerFT_zvk',
    appId: '1:808859481275:ios:39b4d3cf42cd0f23dae59e',
    messagingSenderId: '808859481275',
    projectId: 'go-app-3255c',
    databaseURL: 'https://go-app-3255c-default-rtdb.firebaseio.com',
    storageBucket: 'go-app-3255c.firebasestorage.app',
    iosBundleId: 'com.example.goDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSFFVBcx3qF7kakHhkw8g6ZxQ4xZDZ-MY',
    appId: '1:808859481275:web:a17d438ec4cd08addae59e',
    messagingSenderId: '808859481275',
    projectId: 'go-app-3255c',
    authDomain: 'go-app-3255c.firebaseapp.com',
    databaseURL: 'https://go-app-3255c-default-rtdb.firebaseio.com',
    storageBucket: 'go-app-3255c.firebasestorage.app',
    measurementId: 'G-DE27M7HFFK',
  );
}
